version: 2.0
jobs:
  # build-and-test:
  #   docker:
  #     - image: cimg/node:14.20.0
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         key: dependency=cache={{ checksum "package-lock.json" }}
  #     - run:
  #         name: install-npm-modules
  #         command: 'npm install'
  #     - save_cache:
  #         key: dependency-cache-{{ checksum "package-lock.json" }}
  #         paths: 
  #         - ./node_modules
  #     - run:
  #         name: test
  #         command: 'npm run test:ci'
  build-deploy-prod:
    docker:
      - image: cimg/node:18.18.0
    steps:
      - checkout
      - restore_cache:
          key: dependency=cache={{ checksum "package-lock.json" }}
      - run:
          name: install_packages
          command: |
            make install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths: 
            - ./node_modules
      - run:
          name: make_build
          command: |
            make build
      - run:
          name: deploy-heroku-prod
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PIPELINE.git main
workflows:
  version: 2
  build-test-deploy-prod:
    jobs:
      # - build-and-test:
      #       filters:
      #         branches:
      #           only: main
      - build-deploy-prod:
            # requires:
            #   - build-and-test
            filters:
              branches:
                only: main
      
