version: 2.1
orbs:
  heroku: circleci/heroku@2.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.18.0
    steps:
      - checkout
      - restore_cache:
          key: dependency=cache={{ checksum "package-lock.json" }}
      - run:
          name: install_packages
          command: |
            make install
      - run:
          name: make_packages
          command: |
            make build
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths: 
            - ./node_modules

workflows:
  version: 2
  test-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: main
      - heroku/deploy-via-git:
          requires:
            - build-and-test
          app-name: $HEROKU_APP_NAME
      
