version: 2.1
orbs:
  heroku: circleci/heroku@2.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.18.0
    steps:
      - checkout
      - restore_cache:
          key: dependency=cache={{ checksum "package-lock.json" }}
      - run:
          name: install_packages
          command: |
            make install
      - run:
          name: make_packages
          command: |
            make build
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths: 
            - ./node_modules

workflows:
  version: 2
  test-deploy-uat:
    jobs:
      - build-and-test:
          name: 'build and test uat'
          filters:
            branches:
              only: uat
      - heroku/deploy-via-git:
          name: 'deploy to uat'
          requires:
            - 'build and test uat'
          app-name: $HEROKU_UAT_APP_NAME
          filters:
            branches:
              only: uat
  test-deploy-prod:
    jobs:  
      - build-and-test:
          name: 'build and test prod'
          filters:
            tags:
              only: /^v.*/
            branches:
              only: main
      - heroku/deploy-via-git:
          name: 'deploy to prod'
          requires:
            - 'build and test prod'
          app-name: $HEROKU_APP_NAME
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/